[project]
name = "leo-sorting"
version = "0.1.0"
description = "The leo-sorting package"
license = "MIT"

[remote]
author = "[AUTHOR]" # Add your Aleo Package Manager username, team's name, or organization's name.
